CC = gcc

all: SimpleShell SimpleScheduler

SimpleScheduler: SimpleScheduler.c
	$(CC) -o SimpleScheduler SimpleScheduler.c

SimpleShell: SimpleShell.c
	$(CC) -o SimpleShell SimpleShell.c

clean:
	rm -f SimpleShell SimpleScheduler